application: hayashih-hrd
version: 4
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: jinja2
  version: latest

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /bootstrap
  static_dir: bootstrap

- url: /gominohi/.*
  script: gominohi_main.app

